// All dashboard derivations live in @examify-tms/shared so the mobile client
// can reuse them. Re-exported here to keep existing "../lib" imports working.
export {
  previousPeriodLabel,
  currentPeriodLabel,
  formatCurrencyWhole,
  formatHours,
  deltaPercent,
  currentPeriodRange,
  plannedLessons,
  expectedIncomeFromLessons,
  findCurrentLesson,
  upcomingLessons,
  nextLesson,
  timeUntil,
  todoLessons,
  lessonChecklistTodos,
  lessonTimeRange,
  relativeDayLabel,
  buildChartData,
  sum,
  mean,
  peak,
  todayBucketLabel,
  isDenseSeries,
  type LessonChecklistItem,
  type ChartPoint,
} from "@examify-tms/shared";
