// Lesson/event form schema + form→API mappers live in @examify-tms/shared.
export {
  DAYS,
  DAY_LABELS,
  DAY_FULL_LABELS,
  DURATION_PRESETS,
  eventFormSchema,
  toCreateLessonRequest,
  toCreateRecurringLessonRequest,
  minutesBetween,
  intervalWeeksFor,
  estimateOccurrenceCount,
  describeRecurrence,
  describeOneOff,
  formatTime12h,
  timePlusMinutes,
  type EventFormData,
  type Repeat,
  type RecurringSlot,
} from "@examify-tms/shared";
