import { calendar } from "../config/google";
import { calendar_v3 } from "googleapis";

export interface GenerateMeetLinkOptions {
  /** ISO 8601 start. Defaults to "now" when omitted. */
  startDateTime?: string;
  /** Duration in minutes. Defaults to 30 when omitted. */
  durationMinutes?: number;
}

export interface GeneratedMeeting {
  meetingLink: string;
  /** ID of the backing Google Calendar event (owned by the service account). */
  calendarEventId: string;
}

/**
 * Create a Google Calendar event with a Hangouts/Meet conference and return
 * the generated Meet URL. The event is created in the service account's own
 * calendar (or GOOGLE_CALENDAR_ID), so the Meet room is fully usable but the
 * event itself isn't visible in the tutor's personal calendar.
 *
 * Conference provisioning is asynchronous, so if the insert response comes
 * back "pending" we re-fetch the event once before giving up.
 */
export async function generateMeetLink(
  opts: GenerateMeetLinkOptions = {},
): Promise<GeneratedMeeting> {
  const start = opts.startDateTime ? new Date(opts.startDateTime) : new Date();
  const durationMinutes = opts.durationMinutes ?? 30;
  const end = new Date(start.getTime() + durationMinutes * 60_000);

  const cal = calendar();
  const calendarId = process.env.GOOGLE_CALENDAR_ID || "primary";

  // The valid conference types differ per account/calendar. Ask the calendar
  // which solutions it supports and prefer a Meet/video one; otherwise let
  // Google pick its default (omit conferenceSolutionKey).
  const solutionType = await pickConferenceSolutionType(cal, calendarId);

  const requestBody: calendar_v3.Schema$Event = {
    summary: "Examify lesson",
    description: "Meeting generated by Examify TMS",
    start: { dateTime: start.toISOString() },
    end: { dateTime: end.toISOString() },
    conferenceData: {
      createRequest: {
        requestId: `examify-${start.getTime()}`,
        ...(solutionType
          ? { conferenceSolutionKey: { type: solutionType } }
          : {}),
      },
    },
  };

  const insert = await cal.events.insert({
    calendarId,
    conferenceDataVersion: 1,
    requestBody,
  });

  const eventId = insert.data.id;
  if (!eventId) {
    throw new Error("Google Calendar did not return an event id.");
  }

  let event = insert.data;

  // Conference provisioning is asynchronous — if no link resolved yet, wait a
  // moment and re-fetch the event once.
  if (!extractMeetLink(event.conferenceData)) {
    await delay(1500);
    const refetch = await cal.events.get({ calendarId, eventId });
    event = refetch.data;
  }

  const meetingLink = extractMeetLink(event.conferenceData);
  if (!meetingLink) {
    throw new Error(
      "Google Calendar did not provision a Meet link in time. Please try again.",
    );
  }

  return { meetingLink, calendarEventId: eventId };
}

const MEET_SOLUTION_TYPES = ["hangoutsMeet", "eventHangout"];

/**
 * Look up the conference solutions the calendar allows and return a type that
 * yields a Google Meet room. Prefers an explicit Meet solution, falls back to
 * any allowed solution, and returns undefined if none are listed (letting
 * Google apply its default — which for Meet-enabled accounts is Meet).
 */
async function pickConferenceSolutionType(
  cal: ReturnType<typeof calendar>,
  calendarId: string,
): Promise<string | undefined> {
  try {
    const { data } = await cal.calendars.get({ calendarId });
    const types = (data.conferenceProperties?.allowedConferenceSolutionTypes ?? []).filter(
      (t): t is string => Boolean(t),
    );

    const meet = types.find((t) => MEET_SOLUTION_TYPES.includes(t));
    if (meet) return meet;
    return types[0];
  } catch {
    // If we can't read calendar settings, let Google pick its default.
    return undefined;
  }
}

/** Pull the Meet (video) entry point URI out of the conference data, if present. */
function extractMeetLink(
  conferenceData?: calendar_v3.Schema$ConferenceData | null,
): string | undefined {
  if (!conferenceData?.entryPoints) {
    return undefined;
  }
  const video = conferenceData.entryPoints.find(
    (e) => e.entryPointType === "video",
  );
  const uri = video?.uri ?? conferenceData.entryPoints[0]?.uri;
  return uri ?? undefined;
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
