import { google, calendar_v3 } from "googleapis";
import { getOAuth2ClientForUser } from "../config/googleOAuth";
import { getGoogleConnection } from "./userService";

export interface GenerateMeetLinkOptions {
  /** ISO 8601 start. Defaults to "now" when omitted. */
  startDateTime?: string;
  /** Duration in minutes. Defaults to 30 when omitted. */
  durationMinutes?: number;
}

export interface GeneratedMeeting {
  meetingLink: string;
  /** ID of the backing Google Calendar event in the tutor's own calendar. */
  calendarEventId: string;
}

/** Thrown when a tutor hasn't connected their Google account yet. */
export class GoogleNotConnectedError extends Error {
  constructor() {
    super("Connect your Google account first to generate a meeting link.");
    this.name = "GoogleNotConnectedError";
  }
}

/**
 * Create a Google Calendar event (with a Meet conference) in the tutor's OWN
 * calendar, using their stored OAuth refresh token, and return the Meet URL.
 *
 * Meet provisioning is asynchronous, so if the insert response doesn't yet
 * carry a link we re-fetch the event once before giving up.
 */
export async function generateMeetLinkForUser(
  uid: string,
  opts: GenerateMeetLinkOptions = {},
): Promise<GeneratedMeeting> {
  const connection = await getGoogleConnection(uid);
  if (!connection) {
    throw new GoogleNotConnectedError();
  }

  const start = opts.startDateTime ? new Date(opts.startDateTime) : new Date();
  const durationMinutes = opts.durationMinutes ?? 30;
  const end = new Date(start.getTime() + durationMinutes * 60_000);

  const auth = getOAuth2ClientForUser(connection.refreshToken);
  const cal = google.calendar({ version: "v3", auth });
  const calendarId = "primary"; // the tutor's own calendar

  const requestBody: calendar_v3.Schema$Event = {
    summary: "Examify lesson",
    description: "Meeting generated by Examify TMS",
    start: { dateTime: start.toISOString() },
    end: { dateTime: end.toISOString() },
    conferenceData: {
      createRequest: {
        requestId: `examify-${start.getTime()}`,
        conferenceSolutionKey: { type: "hangoutsMeet" },
      },
    },
  };

  const insert = await cal.events.insert({
    calendarId,
    conferenceDataVersion: 1,
    requestBody,
  });

  const eventId = insert.data.id;
  if (!eventId) {
    throw new Error("Google Calendar did not return an event id.");
  }

  let event = insert.data;

  if (!extractMeetLink(event.conferenceData)) {
    await delay(1500);
    const refetch = await cal.events.get({ calendarId, eventId });
    event = refetch.data;
  }

  const meetingLink = extractMeetLink(event.conferenceData);
  if (!meetingLink) {
    throw new Error(
      "Google Calendar did not provision a Meet link in time. Please try again.",
    );
  }

  return { meetingLink, calendarEventId: eventId };
}

/** Pull the Meet (video) entry point URI out of the conference data, if present. */
function extractMeetLink(
  conferenceData?: calendar_v3.Schema$ConferenceData | null,
): string | undefined {
  if (!conferenceData?.entryPoints) {
    return undefined;
  }
  const video = conferenceData.entryPoints.find(
    (e) => e.entryPointType === "video",
  );
  const uri = video?.uri ?? conferenceData.entryPoints[0]?.uri;
  return uri ?? undefined;
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
