import { randomUUID } from "node:crypto";
import { google, calendar_v3 } from "googleapis";
import { getOAuth2ClientForUser } from "../config/googleOAuth";
import { getGoogleConnection } from "./userService";
import {
  getLessonByIdFromFirestore,
  setLessonGoogleEventId,
} from "./lessonService";

export interface GenerateMeetLinkOptions {
  /** ISO 8601 start. Defaults to "now" when omitted. */
  startDateTime?: string;
  /** Duration in minutes. Defaults to 30 when omitted. */
  durationMinutes?: number;
  /**
   * ID of the lesson this Meet link is for. When provided, the Meet
   * conference is attached to the lesson's existing Google Calendar event
   * (if it has one) instead of creating a duplicate event.
   */
  lessonId?: string;
}

export interface GeneratedMeeting {
  meetingLink: string;
  /** ID of the backing Google Calendar event in the tutor's own calendar. */
  calendarEventId: string;
}

/** Thrown when a tutor hasn't connected their Google account yet. */
export class GoogleNotConnectedError extends Error {
  constructor() {
    super("Connect your Google account first to generate a meeting link.");
    this.name = "GoogleNotConnectedError";
  }
}

/**
 * Create (or attach to) a Google Calendar event with a Meet conference in the
 * tutor's OWN calendar, using their stored OAuth refresh token, and return the
 * Meet URL.
 *
 * When `opts.lessonId` is provided and that lesson already has a backing
 * Google Calendar event (`googleCalendarEventId`), the Meet conference is
 * patched onto that existing event — so generating a Meet link for a lesson
 * does NOT create a second entry on the tutor's calendar. If the lesson has no
 * backing event (or none is provided), a fresh event is created; when a
 * lessonId was given, the new event id is persisted on the lesson.
 *
 * Meet provisioning is asynchronous, so if the response doesn't yet carry a
 * link we re-fetch the event once before giving up.
 */
export async function generateMeetLinkForUser(
  uid: string,
  opts: GenerateMeetLinkOptions = {},
): Promise<GeneratedMeeting> {
  const connection = await getGoogleConnection(uid);
  if (!connection) {
    throw new GoogleNotConnectedError();
  }

  const auth = getOAuth2ClientForUser(connection.refreshToken);
  const cal = google.calendar({ version: "v3", auth });
  const calendarId = "primary"; // the tutor's own calendar

  // Resolve the lesson (if any) so we can reuse its existing calendar event
  // instead of creating a duplicate.
  const lesson = opts.lessonId ? await getLessonByIdFromFirestore(opts.lessonId) : null;

  const start = lesson
    ? new Date(lesson.startDateTime as any)
    : opts.startDateTime
      ? new Date(opts.startDateTime)
      : new Date();
  const durationMinutes = lesson
    ? lesson.durationMinutes
    : (opts.durationMinutes ?? 30);
  const end = new Date(start.getTime() + durationMinutes * 60_000);

  const conferenceData: calendar_v3.Schema$ConferenceData = {
    createRequest: {
      // Google keys conference creation on this requestId per OAuth client
      // (not per event), so a colliding id returns another lesson's Meet
      // conference. It must be unique per request.
      requestId: `examify-${lesson ? `lesson-${lesson.id}-` : ""}${randomUUID()}`,
      conferenceSolutionKey: { type: "hangoutsMeet" },
    },
  };

  let eventId: string | undefined;
  let event: calendar_v3.Schema$Event | undefined;

  // Prefer attaching Meet to the lesson's existing calendar event.
  if (lesson?.googleCalendarEventId) {
    try {
      const patch = await cal.events.patch({
        calendarId,
        eventId: lesson.googleCalendarEventId,
        conferenceDataVersion: 1,
        requestBody: { conferenceData },
      });
      eventId = patch.data.id ?? lesson.googleCalendarEventId;
      event = patch.data;
    } catch (error) {
      // If the stored event was deleted on Google's side (404/410), fall
      // through to creating a fresh event below; otherwise rethrow.
      if (!isGoogleEventNotFound(error)) throw error;
    }
  }

  // No existing event to reuse — create a new one.
  if (!eventId) {
    const requestBody: calendar_v3.Schema$Event = {
      summary: "Examify lesson",
      description: "Meeting generated by Clastor",
      start: { dateTime: start.toISOString() },
      end: { dateTime: end.toISOString() },
      conferenceData,
    };

    const insert = await cal.events.insert({
      calendarId,
      conferenceDataVersion: 1,
      requestBody,
    });

    eventId = insert.data.id ?? undefined;
    if (!eventId) {
      throw new Error("Google Calendar did not return an event id.");
    }
    event = insert.data;

    // Persist the new event id on the lesson so future syncs reuse it.
    if (lesson) {
      await setLessonGoogleEventId(lesson.id, eventId);
    }
  }

  // Meet provisioning is async — give it a moment and refetch if needed.
  if (!event || !extractMeetLink(event.conferenceData)) {
    await delay(1500);
    const refetch = await cal.events.get({ calendarId, eventId });
    event = refetch.data;
  }

  const meetingLink = extractMeetLink(event.conferenceData);
  if (!meetingLink) {
    throw new Error(
      "Google Calendar did not provision a Meet link in time. Please try again.",
    );
  }

  return { meetingLink, calendarEventId: eventId };
}

/**
 * True when a Google Calendar API error indicates the target event no longer
 * exists (404 soft-deleted or 410 permanently purged). Mirrors the helper in
 * googleCalendarService, used here to detect a stale stored event id.
 */
function isGoogleEventNotFound(error: unknown): boolean {
  const code =
    (error as { code?: number; response?: { status?: number } } | null)?.code ??
    (error as { response?: { status?: number } } | null)?.response?.status;
  return code === 404 || code === 410;
}

/** Pull the Meet (video) entry point URI out of the conference data, if present. */
function extractMeetLink(
  conferenceData?: calendar_v3.Schema$ConferenceData | null,
): string | undefined {
  if (!conferenceData?.entryPoints) {
    return undefined;
  }
  const video = conferenceData.entryPoints.find(
    (e) => e.entryPointType === "video",
  );
  const uri = video?.uri ?? conferenceData.entryPoints[0]?.uri;
  return uri ?? undefined;
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
